services:
  phpinfo:
    container_name: phpinfo
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - "../src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.phpinfo.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.phpinfo.entrypoints=websecure"
      - "traefik.http.routers.phpinfo.tls.certresolver=myresolver"
    networks:
      web:
      mariadb:
networks:
  web:
    name: web
    external: true
